# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NEWSLETTER CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          frontend/package-lock.json
          backend/package-lock.json
    
    # Install root dependencies
    - name: Install root dependencies
      run: npm ci
    
    # Install and build frontend
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build frontend
      run: |
        cd frontend
        CI=true npm run build
    
    # Install and test backend
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    # Optional: Run tests if they exist
    - name: Test frontend
      run: |
        cd frontend
        npm test -- --coverage --ci --testResultsProcessor="jest-junit" --watchAll=false
      continue-on-error: true
    
    - name: Test backend  
      run: |
        cd backend
        npm test --if-present
      continue-on-error: true
